### PR TITLE
Update for Django 2

### PR DESCRIPTION
**Pull request by CoryADavis**
I think it would be useful to update the library for Django 2, and have people using older versions use a previous build, like what was done in the past. This library, though old, has features that would otherwise take a long time for someone to implement.

Edit - Added some conditionals to demo and library code to keep Django 1.9 support

The changes here pass current tests, and I validated they work on a personal project. Which is good, because there was a bug with m2m fields that isn't covered in the test cases.

### CODE REVIEW

**Comment by bufke** [comment]
I'll try to find some time to review. I agree this project still has some use that I've not seen other projects do. However I don't have any active needs for it which makes time hard to justify. Help is welcome! As for Django support - I'd say only currently supported versions need to be tested against. 1.11, 2.0, and 2.1. Anyone using another version can just use a older version and the change can be noted.

**Comment by timomeara** [comment]
is anyone working on merging this pr?

**Comment by bufke** [comment]
No - would you want to review it?

**Comment by jankyupeblik** [comment]
Looks okay to me. Not very many changes at all. The primary changes required are the first commit's addition of `on_delete` arguments. @bufke

`django-simple-import` from PyPI does not presently work with the latest LTS version of Django (`2.2` as of writing). This PR solves the problem.

**Pull request merged**
